version: '3.9'

services:
  app:
    image: node:18
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /app/node_modules/
    ports:
      - 3030:3000
    command: bash -c "yarn install && yarn prisma generate && yarn build && yarn start:prod"